/*
 * Emre Motan
 * 6/12/2014
 * 
 * Even Fibonacci numbers
 * Problem 2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *  
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 * ANSWER: 4613762
 */
namespace ProjectEuler
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Forms;

    class P2
    {
        public void Run()
        {
            int n = 4000000;

            int sum = 0;

            List<int> fibs = new List<int>();

            // Seed the Fibonacci sequence
            fibs.Add(1);
            fibs.Add(2);

            // Generate a list of all Fibonacci numbers under "n"
            int keep_looping = 1;
            do
            {
                int fib_cnt = fibs.Count;

                int fib = fibs[fib_cnt - 1] + fibs[fib_cnt - 2];

                if (fib >= n)
                {
                    keep_looping = 0;
                }
                else
                {
                    fibs.Add(fib);
                }

            } while (keep_looping == 1);

            // Loop through the list and add the even numbers to sum
            foreach (var fib in fibs)
            {
                if (fib % 2 == 0)
                {
                    sum += fib;
                }
            }

            Console.WriteLine("Sum of even Fibonacci numbers under {0}: {1}", n, sum);
            Console.ReadLine();

        }
    }
}